"""
Next-generation Stage-2 comparison with validation AUC-primary selection.

Task:
    bacterial pneumonia (negative=0) vs viral pneumonia (positive=1)

This script DOES NOT train new models. It audits and compares the saved
validation/test prediction files generated by the existing Stage-2 training
scripts. It calculates 2,000 filename-group bootstrap confidence intervals for
all main metrics, chooses an operational Stage-2 model using validation data
only, and exports a unified selected-model prediction file.

Recommended location:
    <project-root>\\src\\stage2_compare_select_nextgen.py

Run:
    python -m src.stage2_compare_select_nextgen ^
        --project-root "<project-root>" ^
        --reps 2000

Important:
1. Positive class = viral pneumonia.
2. Negative class = bacterial pneumonia.
3. The fixed exploratory test data are never used for model or threshold selection.
4. Models whose scores depend on ranking the entire test cohort are excluded
   from operational selection by default.
5. The group-OOF fixed stack is reported as a benchmark, but is not mixed into
   the ordinary held-out-validation ranking by default.
"""

from __future__ import annotations

import argparse
import json
from dataclasses import dataclass
from pathlib import Path
from typing import Dict, Iterable, List, Mapping, Optional, Sequence, Tuple

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd


SEED = 20260720

# Existing artifact names in the current project.
EXPECTED_MODELS: Tuple[str, ...] = (
    "intensity_logistic",
    "hog_linear_svm",
    "small_cnn",
    "resnet18",
    "efficientnet_b0",
    "pneunet",
    "pneunet_no_attention",
    "pneunet_avg_pool",
    "deep_ensemble",
    "pneunet_hr",
    "densenet121_avg",
    "pneunet_v2",
    "pneunet_eq",
    "cernet_resnet50",
    "cernet_resnet50_tuned",
    "pneunet_embedding_svm",
    "xrv_densenet121",
    "convnext_tiny_384",
    "efficientnet_b3_384",
)

# These are ordinary per-image models or case-independent per-image ensembles.
# They may be selected when both val/test predictions are available.
DEFAULT_SELECTION_ELIGIBLE: Tuple[str, ...] = (
    "intensity_logistic",
    "hog_linear_svm",
    "small_cnn",
    "resnet18",
    "efficientnet_b0",
    "pneunet",
    "pneunet_no_attention",
    "pneunet_avg_pool",
    "deep_ensemble",
    "pneunet_hr",
    "densenet121_avg",
    "pneunet_v2",
    "pneunet_eq",
    "cernet_resnet50",
    "cernet_resnet50_tuned",
    "xrv_densenet121",
    "convnext_tiny_384",
    "efficientnet_b3_384",
)

# The historical feature classifier uses within-cohort rank transforms for its
# saved test probabilities. It is useful as a benchmark but is not an
# independent per-case operational score.
COHORT_RANK_MODELS = {
    "pneunet_embedding_svm",
}

# Historical stacks that should never be selected or included in the current
# primary table.
UNSAFE_OR_DEPRECATED_MODELS = {
    "validation_stacked_ensemble",
    "fixed_quantile_stacked_ensemble",
    "validation_stacking",
    "stacked_ensemble",
}

DISPLAY_NAMES = {
    "intensity_logistic": "Intensity logistic",
    "hog_linear_svm": "HOG linear SVM",
    "small_cnn": "Small CNN",
    "resnet18": "ResNet-18",
    "efficientnet_b0": "EfficientNet-B0",
    "pneunet": "PneuNet",
    "pneunet_no_attention": "PneuNet no attention",
    "pneunet_avg_pool": "PneuNet average pooling",
    "deep_ensemble": "Deep ensemble",
    "pneunet_hr": "PneuNet-HR",
    "densenet121_avg": "DenseNet121 average pooling",
    "pneunet_v2": "PneuNet-v2",
    "pneunet_eq": "PneuNet-EQ",
    "cernet_resnet50": "CER-Net baseline",
    "cernet_resnet50_tuned": "CER-Net tuned",
    "pneunet_embedding_svm": "PneuNet embedding classifier",
    "group_oof_fixed_stack": "Group-OOF fixed stack",
    "xrv_densenet121": "XRV DenseNet121",
    "convnext_tiny_384": "ConvNeXt-Tiny 384",
    "efficientnet_b3_384": "EfficientNet-B3 384",
}

METRIC_NAMES = (
    "roc_auc",
    "pr_auc",
    "accuracy",
    "balanced_accuracy",
    "sensitivity",
    "specificity",
    "f1",
    "brier",
)


@dataclass
class PredictionPair:
    model: str
    validation: pd.DataFrame
    test: pd.DataFrame
    validation_file: Path
    test_file: Path


def ensure_dirs(root: Path) -> None:
    (root / "reports").mkdir(parents=True, exist_ok=True)
    (root / "reports" / "figures").mkdir(parents=True, exist_ok=True)
    (root / "artifacts").mkdir(parents=True, exist_ok=True)


def validate_manifest(manifest: pd.DataFrame) -> None:
    required = {"path", "patient", "split", "stage1", "subtype"}
    missing = sorted(required - set(manifest.columns))
    if missing:
        raise ValueError(f"manifest.csv缺少字段: {missing}")

    if manifest["path"].duplicated().any():
        examples = manifest.loc[
            manifest["path"].duplicated(), "path"
        ].head().tolist()
        raise ValueError(f"manifest.csv存在重复path，例如: {examples}")

    pneumonia = manifest[manifest["stage1"] == 1]
    invalid_subtypes = sorted(
        set(pneumonia["subtype"].astype(str))
        - {"bacterial", "viral"}
    )
    if invalid_subtypes:
        raise ValueError(
            f"Stage-2肺炎数据包含异常subtype: {invalid_subtypes}"
        )

    if pneumonia["patient"].isna().any():
        raise ValueError("Stage-2数据存在缺失filename group")

    group_split_count = pneumonia.groupby("patient")["split"].nunique()
    if (group_split_count > 1).any():
        bad = group_split_count[group_split_count > 1].head().index.tolist()
        raise ValueError(f"同一filename group跨越数据子集，例如: {bad}")


def stage2_frame(manifest: pd.DataFrame, split: str) -> pd.DataFrame:
    frame = manifest[
        (manifest["stage1"] == 1)
        & (manifest["split"].astype(str) == split)
    ].copy()
    frame["expected_y"] = (
        frame["subtype"].astype(str) == "viral"
    ).astype(np.int8)
    return frame.reset_index(drop=True)


def read_prediction_file(
    path: Path,
    expected: pd.DataFrame,
    model: str,
    split: str,
) -> pd.DataFrame:
    frame = pd.read_csv(path)
    required = {"path", "y_true", "probability"}
    missing = sorted(required - set(frame.columns))
    if missing:
        raise ValueError(
            f"{model}/{split}预测文件缺少字段: {missing}; file={path}"
        )

    frame = frame[["path", "y_true", "probability"]].copy()
    frame["path"] = frame["path"].astype(str)
    frame["y_true"] = frame["y_true"].astype(np.int8)
    frame["probability"] = pd.to_numeric(
        frame["probability"], errors="coerce"
    )

    if frame["path"].duplicated().any():
        raise ValueError(f"{model}/{split}存在重复path: {path}")

    if frame["probability"].isna().any():
        examples = frame.loc[
            frame["probability"].isna(), "path"
        ].head().tolist()
        raise ValueError(
            f"{model}/{split}存在空或非法概率，例如: {examples}"
        )

    if not frame["probability"].between(0.0, 1.0).all():
        bad = frame.loc[
            ~frame["probability"].between(0.0, 1.0),
            ["path", "probability"],
        ].head()
        raise ValueError(
            f"{model}/{split}概率不在[0,1]:\n{bad}"
        )

    check = expected[
        ["path", "expected_y"]
    ].merge(
        frame,
        on="path",
        how="left",
        validate="one_to_one",
    )

    if check["probability"].isna().any():
        missing_paths = check.loc[
            check["probability"].isna(), "path"
        ].head().tolist()
        raise ValueError(
            f"{model}/{split}缺少"
            f"{int(check['probability'].isna().sum())}张预测，例如: "
            f"{missing_paths}"
        )

    if len(frame) != len(expected):
        extra = sorted(set(frame["path"]) - set(expected["path"]))
        raise ValueError(
            f"{model}/{split}预测数量不等于预期。"
            f"pred={len(frame)}, expected={len(expected)}, "
            f"extra examples={extra[:5]}"
        )

    if not np.array_equal(
        check["expected_y"].astype(np.int8).to_numpy(),
        check["y_true"].astype(np.int8).to_numpy(),
    ):
        raise ValueError(f"{model}/{split}的y_true与manifest不一致")

    return check[["path", "y_true", "probability"]].copy()


def discover_prediction_pairs(
    root: Path,
    manifest: pd.DataFrame,
    requested_models: Sequence[str],
) -> Tuple[Dict[str, PredictionPair], pd.DataFrame]:
    artifacts = root / "artifacts"
    val_expected = stage2_frame(manifest, "val")
    test_expected = stage2_frame(manifest, "test")

    pairs: Dict[str, PredictionPair] = {}
    status_rows: List[Dict[str, object]] = []

    for model in requested_models:
        if model in UNSAFE_OR_DEPRECATED_MODELS:
            status_rows.append(
                {
                    "model": model,
                    "status": "excluded_deprecated",
                    "validation_file": "",
                    "test_file": "",
                    "reason": "historical unsafe/deprecated stack",
                }
            )
            continue

        val_file = (
            artifacts / f"val_predictions_stage2_{model}.csv"
        )
        test_file = (
            artifacts / f"predictions_stage2_{model}.csv"
        )

        if not val_file.exists() or not test_file.exists():
            status_rows.append(
                {
                    "model": model,
                    "status": "missing",
                    "validation_file": str(val_file),
                    "test_file": str(test_file),
                    "reason": (
                        "validation prediction missing"
                        if not val_file.exists()
                        else "test prediction missing"
                    ),
                }
            )
            continue

        try:
            validation = read_prediction_file(
                val_file,
                val_expected,
                model,
                "val",
            )
            test = read_prediction_file(
                test_file,
                test_expected,
                model,
                "test",
            )
            pairs[model] = PredictionPair(
                model=model,
                validation=validation,
                test=test,
                validation_file=val_file,
                test_file=test_file,
            )
            status_rows.append(
                {
                    "model": model,
                    "status": "ready",
                    "validation_file": str(val_file),
                    "test_file": str(test_file),
                    "reason": "",
                }
            )
        except Exception as error:
            status_rows.append(
                {
                    "model": model,
                    "status": "invalid",
                    "validation_file": str(val_file),
                    "test_file": str(test_file),
                    "reason": str(error),
                }
            )

    return pairs, pd.DataFrame(status_rows)


def binary_roc_auc_numpy(
    y_true: np.ndarray,
    probability: np.ndarray,
) -> float:
    y_true = np.asarray(y_true, dtype=np.int8)
    probability = np.asarray(probability, dtype=np.float64)

    positive = y_true == 1
    negative = y_true == 0
    n_positive = int(positive.sum())
    n_negative = int(negative.sum())
    if n_positive == 0 or n_negative == 0:
        return float("nan")

    order = np.argsort(probability, kind="mergesort")
    sorted_probability = probability[order]
    sorted_y = y_true[order]

    concordant = 0.0
    prior_negative = 0.0
    start = 0
    while start < len(sorted_y):
        end = start + 1
        while (
            end < len(sorted_y)
            and sorted_probability[end] == sorted_probability[start]
        ):
            end += 1
        block = sorted_y[start:end]
        block_positive = float((block == 1).sum())
        block_negative = float((block == 0).sum())
        concordant += block_positive * (
            prior_negative + 0.5 * block_negative
        )
        prior_negative += block_negative
        start = end

    return float(concordant / (n_positive * n_negative))


def average_precision_numpy(
    y_true: np.ndarray,
    probability: np.ndarray,
) -> float:
    y_true = np.asarray(y_true, dtype=np.int8)
    probability = np.asarray(probability, dtype=np.float64)
    n_positive = int((y_true == 1).sum())
    if n_positive == 0:
        return float("nan")

    order = np.argsort(-probability, kind="mergesort")
    ranked_y = y_true[order]
    cumulative_positive = np.cumsum(ranked_y == 1)
    ranks = np.arange(1, len(ranked_y) + 1, dtype=np.float64)
    precision_at_rank = cumulative_positive / ranks
    return float(
        precision_at_rank[ranked_y == 1].sum() / n_positive
    )


def confusion_values(
    y_true: np.ndarray,
    probability: np.ndarray,
    threshold: float,
) -> Dict[str, float]:
    y_true = np.asarray(y_true, dtype=np.int8)
    probability = np.asarray(probability, dtype=np.float64)
    y_pred = probability >= float(threshold)

    tp = int(((y_true == 1) & y_pred).sum())
    fn = int(((y_true == 1) & (~y_pred)).sum())
    tn = int(((y_true == 0) & (~y_pred)).sum())
    fp = int(((y_true == 0) & y_pred).sum())

    sensitivity = tp / (tp + fn) if tp + fn else 0.0
    specificity = tn / (tn + fp) if tn + fp else 0.0
    accuracy = (tp + tn) / len(y_true)
    balanced_accuracy = 0.5 * (sensitivity + specificity)
    denominator = 2 * tp + fp + fn
    f1 = 2 * tp / denominator if denominator else 0.0

    return {
        "accuracy": float(accuracy),
        "balanced_accuracy": float(balanced_accuracy),
        "sensitivity": float(sensitivity),
        "specificity": float(specificity),
        "f1": float(f1),
        "tp": tp,
        "fn": fn,
        "tn": tn,
        "fp": fp,
    }


def metric_values(
    y_true: np.ndarray,
    probability: np.ndarray,
    threshold: float,
) -> Dict[str, float]:
    y_true = np.asarray(y_true, dtype=np.int8)
    probability = np.asarray(probability, dtype=np.float64)

    if len(np.unique(y_true)) < 2:
        raise ValueError("指标计算需要同时包含细菌和病毒类别")

    confusion = confusion_values(
        y_true,
        probability,
        threshold,
    )
    return {
        "roc_auc": binary_roc_auc_numpy(y_true, probability),
        "pr_auc": average_precision_numpy(y_true, probability),
        "accuracy": confusion["accuracy"],
        "balanced_accuracy": confusion["balanced_accuracy"],
        "sensitivity": confusion["sensitivity"],
        "specificity": confusion["specificity"],
        "f1": confusion["f1"],
        "brier": float(np.mean((probability - y_true) ** 2)),
        "tp": confusion["tp"],
        "fn": confusion["fn"],
        "tn": confusion["tn"],
        "fp": confusion["fp"],
    }


def choose_threshold_balanced_accuracy(
    y_true: np.ndarray,
    probability: np.ndarray,
) -> float:
    y_true = np.asarray(y_true, dtype=np.int8)
    probability = np.asarray(probability, dtype=np.float64)

    thresholds = np.unique(
        np.r_[0.0, probability, 1.0]
    ).astype(np.float64)

    best_threshold = 0.5
    best_key = (-np.inf, -np.inf, -np.inf, -np.inf)

    for threshold in thresholds:
        values = confusion_values(
            y_true,
            probability,
            float(threshold),
        )
        key = (
            values["balanced_accuracy"],
            values["f1"],
            min(values["sensitivity"], values["specificity"]),
            float(threshold),
        )
        if key > best_key:
            best_key = key
            best_threshold = float(threshold)

    return best_threshold


def generate_group_bootstrap_indices(
    groups: Sequence[str],
    reps: int,
    seed: int,
) -> List[np.ndarray]:
    group_series = pd.Series(groups, dtype="string")
    if group_series.isna().any():
        raise ValueError("bootstrap group中存在缺失值")

    unique_groups = sorted(group_series.unique().tolist())
    group_to_code = {
        group: index
        for index, group in enumerate(unique_groups)
    }
    codes = np.asarray(
        [group_to_code[str(group)] for group in group_series],
        dtype=np.int64,
    )
    row_ids = np.arange(len(codes), dtype=np.int64)

    rng = np.random.default_rng(seed)
    indices: List[np.ndarray] = []
    for _ in range(reps):
        sampled = rng.integers(
            0,
            len(unique_groups),
            size=len(unique_groups),
        )
        counts = np.bincount(
            sampled,
            minlength=len(unique_groups),
        )
        indices.append(np.repeat(row_ids, counts[codes]))
    return indices


def bootstrap_intervals(
    y_true: np.ndarray,
    probability: np.ndarray,
    threshold: float,
    indices: Sequence[np.ndarray],
) -> Dict[str, Tuple[float, float]]:
    samples: Dict[str, List[float]] = {
        name: [] for name in METRIC_NAMES
    }

    for index in indices:
        y_boot = y_true[index]
        p_boot = probability[index]
        if len(np.unique(y_boot)) < 2:
            continue

        values = metric_values(
            y_boot,
            p_boot,
            threshold,
        )
        for name in METRIC_NAMES:
            value = values[name]
            if np.isfinite(value):
                samples[name].append(float(value))

    intervals: Dict[str, Tuple[float, float]] = {}
    for name, values in samples.items():
        array = np.asarray(values, dtype=np.float64)
        if len(array) == 0:
            intervals[name] = (float("nan"), float("nan"))
        else:
            low, high = np.quantile(array, [0.025, 0.975])
            intervals[name] = (float(low), float(high))
    return intervals


def evaluate_pair(
    pair: PredictionPair,
    threshold: float,
    manifest: pd.DataFrame,
    validation_bootstrap: Sequence[np.ndarray],
    test_bootstrap: Sequence[np.ndarray],
) -> Tuple[Dict[str, object], Dict[str, object]]:
    group_lookup = manifest.set_index("path")["patient"]

    rows: List[Dict[str, object]] = []
    for split, frame, bootstrap in (
        ("val", pair.validation, validation_bootstrap),
        ("test", pair.test, test_bootstrap),
    ):
        working = frame.copy()
        working["group"] = working["path"].map(group_lookup)
        if working["group"].isna().any():
            raise ValueError(
                f"{pair.model}/{split}存在无法匹配的group"
            )

        y_true = working["y_true"].to_numpy(np.int8)
        probability = working["probability"].to_numpy(np.float64)
        point = metric_values(y_true, probability, threshold)
        intervals = bootstrap_intervals(
            y_true,
            probability,
            threshold,
            bootstrap,
        )

        row: Dict[str, object] = {
            "split": split,
            "model": pair.model,
            "display_name": DISPLAY_NAMES.get(
                pair.model, pair.model
            ),
            "n_images": int(len(working)),
            "n_filename_groups": int(
                working["group"].nunique()
            ),
            "threshold": float(threshold),
            "positive_class": "viral",
            "negative_class": "bacterial",
            "operationally_eligible_default": (
                pair.model in DEFAULT_SELECTION_ELIGIBLE
            ),
            "cohort_rank_score": (
                pair.model in COHORT_RANK_MODELS
            ),
            "validation_file": str(pair.validation_file),
            "test_file": str(pair.test_file),
        }

        for name in METRIC_NAMES:
            row[name] = point[name]
            row[f"{name}_ci_low"] = intervals[name][0]
            row[f"{name}_ci_high"] = intervals[name][1]

        row.update(
            {
                "tp_viral": int(point["tp"]),
                "fn_viral": int(point["fn"]),
                "tn_bacterial": int(point["tn"]),
                "fp_bacterial_as_viral": int(point["fp"]),
            }
        )
        rows.append(row)

    return rows[0], rows[1]


def select_model(
    validation_results: pd.DataFrame,
    allow_cohort_rank_model: bool,
    allow_models: Optional[Sequence[str]],
) -> Tuple[pd.Series, pd.DataFrame]:
    candidates = validation_results.copy()

    if allow_models:
        candidates = candidates[
            candidates["model"].isin(set(allow_models))
        ]
    else:
        candidates = candidates[
            candidates["operationally_eligible_default"]
        ]

    if not allow_cohort_rank_model:
        candidates = candidates[
            ~candidates["cohort_rank_score"]
        ]

    if len(candidates) == 0:
        raise RuntimeError(
            "没有可用于Stage-2操作模型选择的候选模型"
        )

    # Stage 2 is a balanced subtype task. The main criterion is the lower
    # bound of validation ROC-AUC, followed by balanced accuracy/F1 lower
    # bounds and then point estimates.
    ranking = candidates.sort_values(
        by=[
            "roc_auc",
            "roc_auc_ci_low",
            "balanced_accuracy",
            "f1",
            "pr_auc",
            "model",
        ],
        ascending=[
            False,
            False,
            False,
            False,
            False,
            True,
        ],
        kind="mergesort",
    ).reset_index(drop=True)
    ranking["selection_rank"] = np.arange(
        1, len(ranking) + 1
    )
    return ranking.iloc[0], ranking


def save_selected_predictions(
    pair: PredictionPair,
    threshold: float,
    root: Path,
) -> None:
    for split, frame in (
        ("val", pair.validation),
        ("test", pair.test),
    ):
        output = frame.copy()
        output["threshold"] = float(threshold)
        output["y_pred"] = (
            output["probability"] >= threshold
        ).astype(np.int8)
        output["predicted_subtype"] = np.where(
            output["y_pred"] == 1,
            "viral",
            "bacterial",
        )
        path = (
            root
            / "artifacts"
            / (
                "val_predictions_stage2_selected.csv"
                if split == "val"
                else "predictions_stage2_selected.csv"
            )
        )
        output.to_csv(path, index=False)


def make_auc_plot(
    test_results: pd.DataFrame,
    selected_model: str,
    output_base: Path,
) -> None:
    plot = test_results.sort_values(
        "roc_auc", ascending=True
    ).copy()
    y_position = np.arange(len(plot))
    lower_error = plot["roc_auc"] - plot["roc_auc_ci_low"]
    upper_error = (
        plot["roc_auc_ci_high"] - plot["roc_auc"]
    )

    fig, ax = plt.subplots(
        figsize=(8.2, max(5.0, 0.48 * len(plot) + 1.5))
    )
    ax.errorbar(
        plot["roc_auc"],
        y_position,
        xerr=np.vstack([lower_error, upper_error]),
        fmt="o",
        capsize=3,
        linewidth=1.2,
    )
    ax.set_yticks(y_position)
    ax.set_yticklabels(plot["display_name"])
    ax.set_xlabel(
        "Locked-test ROC-AUC "
        "(95% filename-group bootstrap CI)"
    )
    ax.set_title(
        "Stage-2 bacterial-versus-viral model comparison"
    )
    ax.grid(axis="x", alpha=0.25)

    for y, (_, row) in zip(y_position, plot.iterrows()):
        if row["model"] == selected_model:
            ax.text(
                row["roc_auc_ci_high"] + 0.003,
                y,
                "selected",
                va="center",
                fontweight="bold",
            )

    fig.tight_layout()
    fig.savefig(output_base.with_suffix(".png"), dpi=400)
    fig.savefig(output_base.with_suffix(".pdf"))
    plt.close(fig)


def benchmark_group_oof_stack(
    root: Path,
    manifest: pd.DataFrame,
    test_bootstrap: Sequence[np.ndarray],
) -> Optional[Dict[str, object]]:
    prediction_path = (
        root
        / "artifacts"
        / "predictions_stage2_group_oof_fixed_stack.csv"
    )
    metrics_path = (
        root
        / "reports"
        / "group_oof_fixed_stack_metrics.json"
    )
    if not prediction_path.exists():
        return None

    test_expected = stage2_frame(manifest, "test")
    prediction = read_prediction_file(
        prediction_path,
        test_expected,
        "group_oof_fixed_stack",
        "test",
    )

    threshold = 0.5
    if metrics_path.exists():
        data = json.loads(
            metrics_path.read_text(encoding="utf-8")
        )
        threshold = float(data.get("threshold", 0.5))

    group_lookup = manifest.set_index("path")["patient"]
    prediction["group"] = prediction["path"].map(group_lookup)
    y_true = prediction["y_true"].to_numpy(np.int8)
    probability = prediction["probability"].to_numpy(np.float64)
    point = metric_values(y_true, probability, threshold)
    intervals = bootstrap_intervals(
        y_true,
        probability,
        threshold,
        test_bootstrap,
    )

    row: Dict[str, object] = {
        "split": "test",
        "model": "group_oof_fixed_stack",
        "display_name": DISPLAY_NAMES[
            "group_oof_fixed_stack"
        ],
        "n_images": int(len(prediction)),
        "n_filename_groups": int(
            prediction["group"].nunique()
        ),
        "threshold": threshold,
        "positive_class": "viral",
        "negative_class": "bacterial",
        "operationally_eligible_default": False,
        "cohort_rank_score": False,
        "validation_file": "",
        "test_file": str(prediction_path),
        "benchmark_note": (
            "Development group-OOF benchmark; excluded from ordinary "
            "held-out-validation selection ranking."
        ),
    }
    for name in METRIC_NAMES:
        row[name] = point[name]
        row[f"{name}_ci_low"] = intervals[name][0]
        row[f"{name}_ci_high"] = intervals[name][1]
    row.update(
        {
            "tp_viral": int(point["tp"]),
            "fn_viral": int(point["fn"]),
            "tn_bacterial": int(point["tn"]),
            "fp_bacterial_as_viral": int(point["fp"]),
        }
    )
    return row


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--project-root",
        type=Path,
        required=True,
    )
    parser.add_argument(
        "--reps",
        type=int,
        default=2000,
    )
    parser.add_argument(
        "--seed",
        type=int,
        default=SEED,
    )
    parser.add_argument(
        "--models",
        nargs="*",
        default=list(EXPECTED_MODELS),
        help=(
            "Artifact model names to inspect. Default: all known "
            "Stage-2 models."
        ),
    )
    parser.add_argument(
        "--selection-models",
        nargs="*",
        default=None,
        help=(
            "Optional explicit operational selection allow-list."
        ),
    )
    parser.add_argument(
        "--allow-cohort-rank-model",
        action="store_true",
        help=(
            "Allow the historical cohort-rank embedding model to be "
            "selected. Not recommended for independent per-case use."
        ),
    )
    args = parser.parse_args()

    root = args.project_root.resolve()
    ensure_dirs(root)

    manifest_path = (
        root / "data" / "processed" / "manifest.csv"
    )
    if not manifest_path.exists():
        raise FileNotFoundError(
            f"未找到manifest: {manifest_path}"
        )

    manifest = pd.read_csv(manifest_path)
    validate_manifest(manifest)

    val_expected = stage2_frame(manifest, "val")
    test_expected = stage2_frame(manifest, "test")

    print(
        f"Stage-2 validation: {len(val_expected)} images, "
        f"{val_expected['patient'].nunique()} filename groups, "
        f"bacterial={(val_expected.expected_y == 0).sum()}, "
        f"viral={(val_expected.expected_y == 1).sum()}",
        flush=True,
    )
    print(
        f"Stage-2 locked test: {len(test_expected)} images, "
        f"{test_expected['patient'].nunique()} filename groups, "
        f"bacterial={(test_expected.expected_y == 0).sum()}, "
        f"viral={(test_expected.expected_y == 1).sum()}",
        flush=True,
    )

    pairs, status = discover_prediction_pairs(
        root,
        manifest,
        args.models,
    )
    status.to_csv(
        root / "reports" / "stage2_prediction_preflight.csv",
        index=False,
    )

    ready = status[status["status"] == "ready"]
    missing = status[status["status"] != "ready"]

    print("\nReady Stage-2 model prediction pairs:")
    if len(ready):
        print(ready[["model", "status"]].to_string(index=False))
    else:
        print("  none")

    if len(missing):
        print("\nMissing/invalid Stage-2 prediction pairs:")
        print(
            missing[
                ["model", "status", "reason"]
            ].to_string(index=False)
        )

    if len(pairs) < 2:
        raise RuntimeError(
            "可比较的Stage-2模型不足2个。请先生成对应的val/test预测。"
        )

    validation_bootstrap = generate_group_bootstrap_indices(
        val_expected["patient"].astype(str).tolist(),
        reps=args.reps,
        seed=args.seed,
    )
    test_bootstrap = generate_group_bootstrap_indices(
        test_expected["patient"].astype(str).tolist(),
        reps=args.reps,
        seed=args.seed + 1,
    )

    validation_rows: List[Dict[str, object]] = []
    test_rows: List[Dict[str, object]] = []

    for model, pair in pairs.items():
        print(
            f"\n[EVAL_START] {model}: "
            f"{args.reps} group-bootstrap draws",
            flush=True,
        )
        threshold = choose_threshold_balanced_accuracy(
            pair.validation["y_true"].to_numpy(np.int8),
            pair.validation["probability"].to_numpy(
                np.float64
            ),
        )
        validation_row, test_row = evaluate_pair(
            pair,
            threshold,
            manifest,
            validation_bootstrap,
            test_bootstrap,
        )
        validation_rows.append(validation_row)
        test_rows.append(test_row)

        pd.DataFrame(validation_rows).to_csv(
            root
            / "reports"
            / "stage2_all_models_validation_ci_partial.csv",
            index=False,
        )
        pd.DataFrame(test_rows).to_csv(
            root
            / "reports"
            / "stage2_all_models_locked_test_ci_partial.csv",
            index=False,
        )

        print(
            f"[EVAL_DONE] {model}: "
            f"threshold={threshold:.6f}, "
            f"val_auc={validation_row['roc_auc']:.6f}, "
            f"test_auc={test_row['roc_auc']:.6f}, "
            f"test_SN={test_row['sensitivity']:.4f}, "
            f"test_SP={test_row['specificity']:.4f}",
            flush=True,
        )

    validation_results = pd.DataFrame(validation_rows)
    test_results = pd.DataFrame(test_rows)

    winner, ranking = select_model(
        validation_results,
        allow_cohort_rank_model=args.allow_cohort_rank_model,
        allow_models=args.selection_models,
    )
    selected_model = str(winner["model"])
    selected_threshold = float(winner["threshold"])

    validation_results["selected_operational_model"] = (
        validation_results["model"] == selected_model
    )
    test_results["selected_operational_model"] = (
        test_results["model"] == selected_model
    )

    validation_results = validation_results.sort_values(
        "roc_auc", ascending=False
    )
    test_results = test_results.sort_values(
        "roc_auc", ascending=False
    )

    # Add group-OOF fixed stack as a separately labelled test benchmark.
    oof_row = benchmark_group_oof_stack(
        root,
        manifest,
        test_bootstrap,
    )
    if oof_row is not None:
        test_results_with_benchmark = pd.concat(
            [test_results, pd.DataFrame([oof_row])],
            ignore_index=True,
        ).sort_values("roc_auc", ascending=False)
    else:
        test_results_with_benchmark = test_results.copy()

    validation_results.to_csv(
        root / "reports" / "stage2_all_models_validation_ci.csv",
        index=False,
    )
    test_results_with_benchmark.to_csv(
        root
        / "reports"
        / "stage2_all_models_locked_test_ci.csv",
        index=False,
    )
    ranking.to_csv(
        root
        / "reports"
        / "stage2_validation_selection_ranking.csv",
        index=False,
    )

    selected_pair = pairs[selected_model]
    save_selected_predictions(
        selected_pair,
        selected_threshold,
        root,
    )

    selected_test_row = test_results[
        test_results["model"] == selected_model
    ].iloc[0].to_dict()

    selected_info = {
        "selected_model": selected_model,
        "display_name": DISPLAY_NAMES.get(
            selected_model, selected_model
        ),
        "selected_threshold": selected_threshold,
        "positive_class": "viral",
        "negative_class": "bacterial",
        "selection_split": "validation",
        "selection_used_locked_test": False,
        "selection_rule": [
            "validation ROC-AUC point estimate",
            "validation ROC-AUC lower 95% CI",
            "validation balanced accuracy",
            "validation F1",
            "validation PR-AUC",
        ],
        "cohort_rank_models_allowed": (
            args.allow_cohort_rank_model
        ),
        "selected_validation_metrics": {
            key: (
                value.item()
                if isinstance(value, np.generic)
                else value
            )
            for key, value in winner.to_dict().items()
        },
        "selected_locked_test_metrics": {
            key: (
                value.item()
                if isinstance(value, np.generic)
                else value
            )
            for key, value in selected_test_row.items()
        },
        "bootstrap": {
            "unit": "namespace-specific filename group",
            "repetitions": args.reps,
            "seed_validation": args.seed,
            "seed_test": args.seed + 1,
            "confidence_interval": "percentile 95%",
        },
        "artifacts": {
            "validation_predictions": (
                "artifacts/val_predictions_stage2_selected.csv"
            ),
            "test_predictions": (
                "artifacts/predictions_stage2_selected.csv"
            ),
            "original_validation_predictions": str(
                selected_pair.validation_file
            ),
            "original_test_predictions": str(
                selected_pair.test_file
            ),
        },
        "important_note": (
            "This is conditional Stage-2 selection on reference-positive "
            "pneumonia images. End-to-end cascade inference must separately "
            "run the selected Stage-2 model on every Stage-1 routed image, "
            "including any routed normal false positives."
        ),
    }

    (
        root / "reports" / "stage2_selected_model.json"
    ).write_text(
        json.dumps(
            selected_info,
            indent=2,
            ensure_ascii=False,
        ),
        encoding="utf-8",
    )

    make_auc_plot(
        test_results_with_benchmark,
        selected_model,
        root
        / "reports"
        / "figures"
        / "stage2_all_models_roc_auc_ci",
    )

    print("\n" + "=" * 100)
    print("Stage-2全部可用模型验证集比较（模型选择仅基于验证集）")
    print(
        validation_results[
            [
                "display_name",
                "threshold",
                "roc_auc",
                "roc_auc_ci_low",
                "roc_auc_ci_high",
                "accuracy",
                "balanced_accuracy",
                "sensitivity",
                "specificity",
                "f1",
            ]
        ].to_string(index=False)
    )

    print("\n" + "=" * 100)
    print(
        f"最终Stage-2操作模型: "
        f"{DISPLAY_NAMES.get(selected_model, selected_model)} "
        f"({selected_model})"
    )
    print(f"验证集确定阈值: {selected_threshold:.8f}")
    print("阳性类别: viral；阴性类别: bacterial")
    print("锁定测试结果:")
    print(
        test_results.loc[
            test_results["model"] == selected_model,
            [
                "roc_auc",
                "roc_auc_ci_low",
                "roc_auc_ci_high",
                "pr_auc",
                "pr_auc_ci_low",
                "pr_auc_ci_high",
                "accuracy",
                "accuracy_ci_low",
                "accuracy_ci_high",
                "balanced_accuracy",
                "balanced_accuracy_ci_low",
                "balanced_accuracy_ci_high",
                "sensitivity",
                "sensitivity_ci_low",
                "sensitivity_ci_high",
                "specificity",
                "specificity_ci_low",
                "specificity_ci_high",
                "f1",
                "f1_ci_low",
                "f1_ci_high",
            ],
        ].to_string(index=False)
    )

    print("\n输出文件:")
    for relative in (
        "reports/stage2_prediction_preflight.csv",
        "reports/stage2_all_models_validation_ci.csv",
        "reports/stage2_all_models_locked_test_ci.csv",
        "reports/stage2_validation_selection_ranking.csv",
        "reports/stage2_selected_model.json",
        "artifacts/val_predictions_stage2_selected.csv",
        "artifacts/predictions_stage2_selected.csv",
        "reports/figures/stage2_all_models_roc_auc_ci.png",
        "reports/figures/stage2_all_models_roc_auc_ci.pdf",
    ):
        print(f"  {root / relative}")


if __name__ == "__main__":
    main()
